#pragma once

// PIWIPER Version Information
// ===========================

#define PIWIPER_VERSION_MAJOR       2
#define PIWIPER_VERSION_MINOR       1
#define PIWIPER_VERSION_PATCH       0
#define PIWIPER_VERSION_BUILD       1

// Version string macros
#define PIWIPER_VERSION_STRINGIFY(x) #x
#define PIWIPER_VERSION_MAKE_STRING(x) PIWIPER_VERSION_STRINGIFY(x)

#define PIWIPER_VERSION_STRING \
    PIWIPER_VERSION_MAKE_STRING(PIWIPER_VERSION_MAJOR) "." \
    PIWIPER_VERSION_MAKE_STRING(PIWIPER_VERSION_MINOR) "." \
    PIWIPER_VERSION_MAKE_STRING(PIWIPER_VERSION_PATCH) "." \
    PIWIPER_VERSION_MAKE_STRING(PIWIPER_VERSION_BUILD)

#define PIWIPER_VERSION_SHORT \
    PIWIPER_VERSION_MAKE_STRING(PIWIPER_VERSION_MAJOR) "." \
    PIWIPER_VERSION_MAKE_STRING(PIWIPER_VERSION_MINOR) "." \
    PIWIPER_VERSION_MAKE_STRING(PIWIPER_VERSION_PATCH)

// Build information
#define PIWIPER_BUILD_DATE          __DATE__
#define PIWIPER_BUILD_TIME          __TIME__
#define PIWIPER_BUILD_CONFIG        "Release"

// Application information
#define PIWIPER_APP_NAME            "PIWIPER"
#define PIWIPER_APP_DESCRIPTION     "Professional Disk Eraser"
#define PIWIPER_APP_COPYRIGHT       "Copyright (c) 2025"
#define PIWIPER_APP_AUTHOR          "PIWIPER Development Team"

// Version info for Windows resources
#define PIWIPER_FILE_VERSION        PIWIPER_VERSION_MAJOR,PIWIPER_VERSION_MINOR,PIWIPER_VERSION_PATCH,PIWIPER_VERSION_BUILD
#define PIWIPER_PRODUCT_VERSION     PIWIPER_VERSION_MAJOR,PIWIPER_VERSION_MINOR,PIWIPER_VERSION_PATCH,PIWIPER_VERSION_BUILD

// Version comparison macros
#define PIWIPER_VERSION_CHECK(major, minor, patch) \
    (PIWIPER_VERSION_MAJOR > (major) || \
     (PIWIPER_VERSION_MAJOR == (major) && PIWIPER_VERSION_MINOR > (minor)) || \
     (PIWIPER_VERSION_MAJOR == (major) && PIWIPER_VERSION_MINOR == (minor) && PIWIPER_VERSION_PATCH >= (patch)))

// Feature flags based on version
#define PIWIPER_HAS_MODERN_UI       PIWIPER_VERSION_CHECK(2, 0, 0)
#define PIWIPER_HAS_DUAL_PROGRESS   PIWIPER_VERSION_CHECK(2, 0, 0)
#define PIWIPER_HAS_VERIFICATION    PIWIPER_VERSION_CHECK(2, 0, 0)
#define PIWIPER_HAS_BACKUP_SYSTEM   PIWIPER_VERSION_CHECK(2, 1, 0)
